######################################################################
# 
#  File        :  $Source: /cvsroot/ijbswa/current/user.action,v $
# 
#  $Id: user.action,v 1.9 2008/03/27 18:27:37 fabiankeil Exp $
#
#  Purpose     :  User-maintained actions file, see
#                 http://www.privoxy.org/user-manual/actions-file.html
#
######################################################################

# This is the place to add your personal exceptions and additions to
# the general policies as defined in default.action. (Here they will be
# safe from updates to default.action.) Later defined actions always
# take precedence, so anything defined here should have the last word.

# See http://www.privoxy.org/user-manual/actions-file.html, or the 
# comments in default.action, for an explanation of what an "action" is
# and what each action does.

# The examples included here either use bogus sites, or have the actual
# rules commented out (with the '#' character). Useful aliases are
# included in the top section as a convenience.

#############################################################################
# Aliases
#############################################################################
{{alias}}
#############################################################################
#
# You can define a short form for a list of permissions - e.g., instead
# of "-crunch-incoming-cookies -crunch-outgoing-cookies -filter -fast-redirects",
# you can just write "shop". This is called an alias.
#
# Currently, an alias can contain any character except space, tab, '=', '{'
# or '}'.
# But please use only 'a'-'z', '0'-'9', '+', and '-'.
#
# Alias names are not case sensitive.
#
# Aliases beginning with '+' or '-' may be used for system action names 
# in future releases - so try to avoid alias names like this.  (e.g. 
# "+crunch-all-cookies" below is not a good name)
#
# Aliases must be defined before they are used.
# 
# These aliases just save typing later:
#
+crunch-all-cookies = +crunch-incoming-cookies +crunch-outgoing-cookies
-crunch-all-cookies = -crunch-incoming-cookies -crunch-outgoing-cookies
 allow-all-cookies  = -crunch-all-cookies -session-cookies-only -filter{content-cookies}
 allow-popups       = -filter{all-popups} -filter{unsolicited-popups}
+block-as-image     = +block{Blocked image request.} +handle-as-image
-block-as-image     = -block

# These aliases define combinations of actions
# that are useful for certain types of sites:
#
fragile     = -block -crunch-all-cookies -filter -fast-redirects -hide-referer -prevent-compression
shop        = -crunch-all-cookies allow-popups

# Your favourite blend of filters:
#
myfilters   = +filter{html-annoyances} +filter{js-annoyances} +filter{all-popups}\
              +filter{webbugs} +filter{banners-by-size}

# Allow ads for selected useful free sites:
#
allow-ads   = -block -filter{banners-by-size} -filter{banners-by-link}
#... etc.  Customize to your heart's content.

## end aliases ########################################################
#######################################################################

# Begin examples: #####################################################

# Say you have accounts on some sites that you visit regularly, and you
# don't want to have to log in manually each time. So you'd like to allow
# persistent cookies for these sites. The allow-all-cookies alias defined
# above does exactly that, i.e. it disables crunching of cookies in any
# direction, and the processing of cookies to make them only temporary.
#
{ allow-all-cookies }
#.sourceforge.net
#sunsolve.sun.com
#slashdot.org
#.yahoo.com
#.msdn.microsoft.com
#.redhat.com

{ +session-cookies-only }
.anonym-to.
.doublepimp.
.filefactory.
.gamebookers.
.gamestar.
.gettyimages.
.google.
.gostats.
.hornyblog.
.hotlinkimage.com
.imagelist.com
.imageshack.
.imagestorex.com
.imagevenue.com
.mediaplex.
.megaporn.com
.nachbarschaft24.net
.nachbarschaftspost.
.noughtypics.us
.opendownload.de
.paidcontent.
.pic-base.com
.picturebang.com
.pixhost.
.rapidpix.net
.stooorage.
.webtrends.
.xxx-testen.de
.zimages.
dsl.1und1.
relink.u



{ +crunch-all-cookies }
.2o7.net
.action4money.
.active-tracking.
.ad*.com
.adultadrevenue.com
.adultbb.
.adultfriendfinder.com
.afftrck.
.apture.
.babyadshop.com
.call-girls.
.cashtrafic.com
.ero-advertising.
.eroticdating.com
.gsadserver.
.highfi-stats.
.hitslink.
.hitsprocessor.
.insuranceplate.com
.partypoker.
.pgmediaserve.
.scorecardresearch.
.smartadserver.com
.statcounter.
.teasernet.
.trafficmasterz.
.verticalnetwork.
.visitdetails.
.webmasterplan.com
.xxxwebtraffic.com
ads.*.
analytics.*.

# Say the site where you do your homebanking needs to open popup
# windows, but you have chosen to kill popups uncoditionally by default.
# This will allow it for your-example-bank.com:
#
{ -filter{all-popups} }

# Some hosts and some file types you may not want to filter for
# various reasons:
#
{ -filter }

# Technical documentation is likely to contain strings that might
# erroneously get altered by the JavaScript-oriented filters:
#
#.tldp.org
#/(.*/)?selfhtml/

# And this stupid host sends streaming video with a wrong MIME type,
# so that Privoxy thinks it is getting HTML and starts filtering:
#



{+block{Layered ads.} +handle-as-empty-document}

.adshot.
.affimo.
.applieda.com
.google.ru
.livejasmin.
.livejasmincdn.
.mediaunder.
.undere.com
.warezlayer.
/js/ulayer.js
/libraries/jspopunder.min.js
jmobqzz.dnsalias.net


# Example of a simple "block" action. Say you've seen an ad on your
# favourite page on example.com that you want to get rid of. You have
# right-clicked the image, selected "copy image location" and pasted
# the URL below while removing the leading http://, into a { +block{reason} }
# section. Note that { +handle-as-image } need not be specified, since
# all URLs ending in .gif will be tagged as images by the general rules
# as set in default.action anyway:
#
{ +block{Nasty ads.} }
# osm
.bksn.se
.adleadevent.com
.adjust.com
.ssacdn.com
.tapjoy.com
.branch.io
supersonicads-[a-z].akamaihd.net
app-measurement.com
.fbcdn.net
.applovin.com
.supersonic.com
.fyber.com

# exoty
.appbaqend.com
.rayjump.com
.unity3d.com
.presage.io
.applike-services.info

# stocard
.stocard.de
.stocard-backend.com

# google actu
.taboola.com

# jv.com
ea.warnerbros.fr

# leboncoin
.tiqcdn.com
.appsflyer.com
.ati-host.net
.accengage.com
.abtasty.com
hit.leboncoin.fr
leboncoin.fr/android_mediametrie

# SmartScale
.umeng.com
.umsns.com

# Huawei Health
.hicloud.com
80.158.20.215
80.158.17.255
80.158.6.113
160.44.207.227
160.44.207.213
.dbankcdn.com

# ES explorer
.estrongs.com

# Slack
.bugsnag.com

# Dailymotion
.dmcdn.net
logger.dailymotion.com
dmxleo.dailymotion.com
id5-sync.com

# Facebook data
## Facebook won't work well... but who use it and want privacy ?
graph.facebook.com

# Denicheur
cdn.pji.nu
.kxcdn.com

# Instagram
.cdninstagram.com
graph.instagram.com
i.instagram.com

# Edenred
.appcenter.ms
services.myedenred.fr

# other
ssl.qrdroid.com
.urbanairship.com
onesignal.com
.batch.com
.inbenta.com
qsurvey.mozilla.com
.melty.fr
.meltygroup.com
#.jwp[a-z][a-z][a-z].com
log.tbs.qq.com
cfg.imtt.qq.com
ccpce-de.consumer.huawei.com
.avast.com
.crashlytics.com
.zergnet.com
.servedby.pixfuture.net
ar.atwola.com
.shared.comcast.net
.iadctest.qwapi.com
.addthis.com
.gravity.com
.taboola.com
.baidu.com

# TriMoon
.ad-x.co.uk
.adkmob.com
.adonline.e-kolay.net
.ads.anyoption.it
.ads.mopub.com
.ads.mp.mydas.mobi
.ads.yahoo.com
.ads.yimg.com
.ads.zynga.com
.adtilt.com
.ashleymadison.com
.conduit.com
.dbreklam2.net
.doubleclick.net
.facebook.com/plugins/ad_unit\.php.*
.gameloft.com/(ads/*|tralala/index\.php\?ad=*)
.google-analytics.com
.googlesyndication.com
.googletagservices.com
.heyzap.com
.hwcdn.net/bundles/.*\.zip
.hwcdn.net/zen/*
.kontera.com
.ksmobile.com
.mobileapptracking.com
.otomobilfirsati.com
.outfit7.com/rest/.*/.*/(offers|videos)/*
.quantserve.com
.startappservice.com
#.sourceforge.net
.trovi.com
.zynga.com/ajax/common_web:pixeltracking*
api.vungle.com/api/.*/(new|requestAd|session.*)
analytics.yahoo.com
cdn.outfit7.com/(promo-nc|vg|button)/*
cm.ksmobile.com
data.flurry.com
delivery.reklamz.com
hit.clickaider.com
hitbox.com
ingameads.gameloft.com
inmobisdk-a.akamaihd.net
live.chartboost.com
marketing-ssl.upsight-api.com
media.admob.com
mobile-collector.newrelic.com
propellerads.com
ptreklam.com.tr
ptreklamssp.com.tr
reklam.memurlar.net
reklamport.com
reklamstore.com
rubiconproject.com
safebrowsing.google.com
safebrowsing-cache.google.com
static.everyplay.com/impact/*
static.mapfactor.com/android-ads/*
track.appsflyer.com
www.finansbank.com.tr/banner/*


syndication.twitter.com
.isonlynews.net
.jasmin.com
.dditservices.com
.linkbucks.com/.....aad/
.linkbucksmedia.com/director/
.preisomat.eu
.etoro.
.cash-flow-international.
.24start.me
.0427d7.
.0llii0g6.
.1378km.de
.214234234234.info
.23mfdoe32rs.
.24smile.
.29bca6cb72a665c8.
.2l322.info
.32red.com
.35l3.info
.35l7.info
.45i73jv6.
.4allclick.ru
.4fcams.
.5l37.info
.5l38.info
.5min.com
.600z.com/aj/*
.6angebot.
.777-partner.
.777partner.
.92l0.info
.99admanager.com
.Bizographics.
.a1.yimg.com
.aad73c550c.
.abendblatt.de/.*teaser
.abv.at
.actionallocator.
.ad-balancer.
.ad-traffic.
.ad.netzquadrat.
.ad6media.
.adalizer.
.adap.tv
.adblade.
.adboost.
.adbooth.
.adbureau.
.adbutler.
.adcash.
.adcell.
.adcount.
.addcontrol.
.addthis.
.addynamo.
.adengage.
.adexprt.
.adform.
.adfux.
.adglamour.
.adhands.
.adition.
.adjames.
.adjug.
.adjuggler.
.adk2.
.adklick.
.adlink.
.adme.de
.admediaking.
.admngronline.
.admoon.
.adorun.
.adperform.
.adpionier.
.adplans.
.adquality.
.adranking.
.adrevolver.
.adriver.
.adrolays.
.adroll.
.ads4finies.
.adsafeprotected.
.adsbyisocket.
.adscale.
.adshopping.
.adsmarket.
.adsniper.
.adspdbl.
.adtech.
.adtraxx.
.adtwothree.
.adultadworld.
.adultgulf.
.adultimate.
.adultpay.net
.adultshop.de
.adulttubetraffic.
.adv.
.advancedadv.
.adverserve.
.advmaker.
.advolution.
.advombat.
.advpoints.
.advprotizer.
.adzerk.
.adzoe.
.adzonk.
.afcyhf.
.affarity.com
.affec.
.affili.
.affiliando.
.affiliatelounge.
.afil.*.yahoo.com
.agentur-wagner.de
.ahcdns.com
.aleadpay.
.allfreegay.com
.amazon-adsystem.
.annienne.com
.anzeigen.abendblatt.de
.anzeigenlieferant.de
.apibuymedia.
.apreces.
.aprement.
.asnetworks.de
.assoc-amazon.
.atdmt.com
.atlassolutions.
.au2m8.
.auto.de/offer/oneofferpromotion
.auxmoney-partnerprogramm.
.avatraffic.
.awempire.
.awmpartners.
.axprod.net
.ba2b687.
.banner.t-online.de
.bannerhost.
.batilo.
.baypops.com
.berlinermedienvertrieb.
.best-pagerank.
.bestevernews.com
.besthitsnow.
.bet365.
.betaffs.
.betarget.
.betclick.
.bfd69dd9.
.biallo1.de
.bidvertiser.
.bigpoint.com
.bild.de/(.*/)partner/
.bild.de/(.*/)shop/
.bild.de/.*/koso/(.*/)
.bild.de/fotos/.*390x125
.bin-layer.
.binlayer.
.binmedia.ru
.bistr4.ru
.blogads.
.blueadvertise.
.bluecava.
.bodyclick.
.bon-kredit.
.bongacams.
.bongacash.
.boostduplicate.info
.bornpay.
.briedenredaktion.de
.broils.ru
.browser-update-meldung.
.brqvld0p.
.btv.at
.c-col.com
.cam4.
.campartner.
.cams.com
.carveac.com
.cash4movie.
.cdapmsfour.
.cdapmsone.
.cdapmssix.
.cdapmsthree.
.cdxndirectopt.
.cdxnn.
.cdxnopt.
.cedexis.
.chaturbate.
.checkout-proxy.info
.ciement.com
.circules.com
.clickintext.
.clickpapa.
.clicksvenue.
.clicksz.
.clickunder.
.clixgalore.
.cloakac.com
.code-proxy.info
.codeproject.com/script/Adm/*
.collective-media.
.commindo-media-ressourcen.
.conduit-banners.
.connexionsecure.
.contact-direct.ru
.contextmatters.
.contextual.
.crowdscience.
.crwdcntrl.
.cumeron.
.cuonemove.info
.customer-support24.
.cxense.
.d03x2011.
.dafficha.
.daisycon.com
.daredac.
.datefree.
.datingadzone.
.dealtime.
.decknetwork.
.demandbase.
.dircash-promost.
.directrev.
.domainprofi.
.domainsponsor.
.donaar.de
.dosugcz.
.doubleclick.
.drss.tv
.ds1.nl
.dsultra.
.dt07.net
.dvd-verleih.info
.dynamic-advertising.
.dynamicyield.
.e-lationshop.
.eads.
.ebuzzing.
.ebuzzingvideo.
.econa.
.econda-monitor.
.edelight.biz
.ee74ff81b44.
.efficienttraffic.
.effiliation.
.efoodsdirect.
.egooad.
.eloqua.
.en25.com
.enfingratuit.
.enoratraffic.
.ero-advertising.
.estiques.
.eurogrand.
.exad.me
.exelator.
.exhost1.me
.exoclick.
.fairfax.com.au
.fairlink.ru
.fapturbo.
.fastclick.
.fastpic./.*\.swf
.fastpromo.in
.faxso.ru
.feedjit.
.filefactory./img/premium/
.filepost.com/static/images/bn/
.filetarget.
.financeads.
.finanzen.net/swf/a_anzeige/
.findmyhome.at/format
.finya.de/shop/
.firstlightera.
.firstload.de/affiliate/*
.flashmediaportal.com
.flashtalking.
.fleshlight-international.
.fleshlight.
.fleshlightstore.
.flipflapflo.
.fncash.
.forex*.com/affiliates/
.forum-maximus./.*\.swf
.fpctraffic2.
.friendscout24./msnquardusercsl.html
.ftd./gujAd/gujAd.js
.fullcirclestudies.
.fulltiltpoker.
.funpic.de/layer.php
.gameoftraffic.
.games724.
.gamesaktuell.de/bcommon/swf/
.gateway-03.com
.gaypicturepost.com
.generic4all.
.getfplayer.com
.getfreebacklinks.
.getresponse.com
.glam./.*\.swf
.glplanet.me
.godaddy.
.gogousenet.com
.goklics.
.gokliks.
.good-teaser.info
.google-analytics.
.googleadservices.
.googlesyndication.
.googletagmanager.
.gorillanation.
.gravity.com
.grifiins.ru
.gsadserver.
.gumgum.
.gunggo.com
.guruads.
.guruplay.
.gutscheine.stern.de
.hash-traff.
.hearstnp.com
.heise.de/avw-bin/ivw/
.heise.de/imgs/.*336x200
.heise.de/ivw-bin/ivw/
.hellobar.com
.hifitest.de/ht_werbebanner
.high-tra-ff.
.hightraonlineff.
.highwebmedia.
.hit.ua
.hklu.info
.hopfeed.
.hubrus.
.i12.de
.ibario.com
.ibillboard.
.iconist.de
.icqadvvk.com
.iftraff105.
.iftraff107.
.ikersont.com
.im-tub.
.im1-tub.
.im2-tub.
.im3-tub.
.im4-tub.
.im5-tub.
.im6-tub.
.imagans.
.imagevenue.com/interstitial.rotate1.js
.imgbabes./(splash|script).php
.imgnip.com/.*\.swf
.imgshots.com/ad.html
.imlive.
.impact-ad.
.impromot.
.imshopping.
.ind.br
.individuad.
.inferalton.
.influads.
.infolinks.
.infowars./.*/x/
.inteliad.
.intensifier.
.intercasino.
.intergi.
.intimetra.
.intimshop.ru
.investingchannel.
.ioam.
.ioiiioi.info
.is-very-good.org
.iss-xund.eu/2012/
.itam-gmbh.com/astracker
.ivwbox.
.jadedi.com
.javbucks.
.jetswap.com
.jivosite.
.jujzh9va.
.kalooga.
.kampyle.
.kaufda.
.kaufda.de
.kaufdown.de
.key-sign.
.kingtraf.
.kitcode.
.kliklink.
.knowone.de/(.*/).*\.(swf)$
.koliser.com
.kolites.
.koluty.
.komdat.com
.koramgame.com
.krutilka.net
.kundwerk.de
.lablue.de/js/adLink*.js
.lacemme.com
.layer-ad.
.layermedia-adserver.
.leadformix.
.lesen.to/layer/
.lifestatic.biz
.liftsk.
.ligatus.
.linkcollider.
.livekeywestmusic.com
.liverail.
.livetraf.
.loading-delivery1.
.loneday.
.loomia.com
.lotto24.de
.love-sms.tv
.m57ku6sm.
.managermest.ru
.marketing-by-phone.
.marktorakel.com/.*\.swf
.maxi-ad.
.maxymiser.
.media-ks.
.mediaip.ru
.mediaplex.
.mediatarget.
.meendocash.
.megamixgroup.
.megastock.
.mehrwertdienstekompetenz.de
.meinprospekt.de
.mestreafiliados.
.metaboli.
.mezima.com
.mgid.com
.mirago.co.uk
.mirando.de
.ml314.
.mlno6.
.mmaaxx.
.mmoga.com
.mobbober.com
.mobidump.com
.moijs.
.morehitserver.
.morenews3.
.moreusers.info
.morevisits.info
.mp-success.com
.mpros.de
.my-dirty-hobby.
.my-proads.
.mydeluxegames.com
.mydirtyhobby.com
.mydownloader.
.mypagerank.
.mytizer.
.mytrannycams.
.naiadsystems.
.nashevideo.info
.nativeads.
.ncjshop.co.uk
.neosmi.ru
.netdebit-counter.
.network-media.
.netxmedia.net
.new-promo2012.
.new-tizer.com
.news.at/prod/.*swf
.news.at/prod/partner
.nimblecommerce.com
.nonstoppartner.
.nrelate.
.nugg.ad
.numberium.
.oclaserver.
.odnoklassniki.ru
.offerandreview.
.okoshechka.net
.olizyr.com
.onadadserver.
.onadmarketing.
.onclickads.
.online-media24.
.openx.org
.optimost.
.otmsrv.com
.ourbesthits.
.ovskin.ru
.pagerankturbo.
.partnercash.
.partnerearning.
.partnermax.
.pay4mobile.
.paymonsters.
.pazoo.com/pazoo-tv/
.pcgames./.*.swf
.peoplesearchaffiliates.
.perfectaudience.
.picbucks.com/track/
.pinkvisualgames.
.piroji.
.pixfuture.
.pixhost.org/image/rotate/
.placement24.
.planet49.com
.planetapes.de
.plista.com
.plugrush.
.pluso.ru
.po.st
.pokersemdeposito.
.poolk.
.popads.
.popclick.net
.poponclick.
.popunder.
.popunderz.
.porndad.
.premiumcpm.
.premiumpromotions.
.privatamateure.com/promotion/
.profitstat.
.profiwin.de
.profstat.
.promedia-click.ru
.promo4partners.
.promocionesweb.
.promoloader.com
.promosrv.com
.propagandafront./.*\.swf
.propellerads.
.propellerpops.
.protizer.
.protrafv2.
.proxysolutions.net/affiliates/
.pub2srv.
.pubexchange.
.pussycash.
.pz-news.de/cms_media/module_wb/
.q1xyxm89.
.quisma.com
.r7e0zhv8.
.rankmonkey.
.reachjunction.
.realdatechat.
.realfreedate.
.realityclick.
.redmoonstudios.de/affiliate/*
.redtram.
.refinedads.
.relatedweboffers.
.relink.us/swf/
.retargetpro.
.returso.
.rghost.ru
.rlcontrol.
.rmbn.
.rocketfuelinc.
.rocketfuelinc.com
.rtcorr.
.rubiconproject.
.ruclicks.
.rulerclick.
.ruscams.
.russianamerica.
.s3exy.com/n..gif
.sceno.
.schnell400euro.
.secure-clicks.
.seoz.info
.serious-cash.
.sexmoney.
.sexpartnerx.
.sextizer.net
.sexuria.com/layer*
.sexypower.
.shareasale.
.sharefoco.com
.shop.tc/
.shop4adomain.com
.shoplove.
.shortnews.de/.*\.swf
.sixsigmatraffic.
.slimspots.
.slimtrade.
.smartadcheck.
.smartadserver.
.smartredirect.
.smi2.ru
.smiletraf.
.smsdate.com
.sochetat.net
.sonobi.
.sparkstudios.
.spotrails.com/ca.php
.spox.
.srvad.
.stableprofit4you.
.stargames.
.stayeda.com
.streamate.
.streamateaccess.
.streamray.com/
.su01.ru
.subscriberconcierge.com
.sunmaker.
.sunnysales.biz
.super-adv.
.sw3m5ncmn.
.sweed.to
.t-online.de/-/id_68029888
.t9media.
.taboolasyndication.
.tafyeta.ru
.tagol2.ru
.targetingnow.
.tbn.ru
.tdstraff.ru
.teasermedia.
.teasernet.
.teaservizio.
.technik-test.biz
.telefoncash.
.telemetryverification.
.textbacklinkexchanges.
.the-adexchange.
.theadex.
.thefilter.com
.thehitsusa.
.theplatform.com
.thumbshots.
.tinsvt.ru
.tipico.
.tisapama.
.tizer-click.
.tizer6.net
.tizerfly.net
.tizergun.
.tizermine.
.tizerplatform.
.tizerset.
.tlvmedia.
.tmserver-1.
.tmserver-2.
.topeuro.
.topstuds.com
.trackvoluum.
.tradedoubler.
.tradetracker.
.traffget.
.traffic-network.
.trafficfacts.
.trafficforce.
.trafficgally.
.trafficholder.
.trafficmanager.net
.trafficmaxx.
.trafficrevenue.
.trafficshop.
.trafficvending.
.traffmedia.
.traffpay.
.traffshop.
.traffstock.
.trafftrade.
.trafgun.
.trafinfo.
.trafovik.ru
.trafsiz.
.trafstock-in.
.traient.
.trakio1.net
.tremormedia.
.tv2n.net
.tvbutler.at/mediafiles/.*swf
.twilightparadox.com
.twinplan.
.tynt.
.uimserv.net
.under-click.
.usermediaclick.
.v2mlred.
.veeseo.
.verticalacuity.com
.verticalnetwork.
.vertoz.
.vghd.com
.vgwort.de
.videogameszone./.*\.swf
.videosz.com
.vidible.tv/prod/tags/
.vidustal.com
.viglink.
.vimgs.ru
.vip-click.info
.vip-traff.
.vipaccess.info
.viragemedia.com
.visit-x.net/promo/
.visualwebsiteoptimizer.
.vk.com
.w3server.eu
.wai.de
.warthunder.ru
.watchever.
.webclickmanager.
.webmasterplan.
.websale.
.webteaser.
.webtradecenter.
.webtrekk.
.welt./multimedia/archive/.*/*328x119*
.welt./sightloader_frame.*
.werbebooster.
.wigetmedia.
.wintotal.de/images/grafikfremd/*
.winwithoption.
.wizard-traffic.
.worldbestcasinosistems.
.worldsoft-cms.info
.wpclktls.
.wt-rotator.
.wt-rotator105.ru
.wt-rotator111.ru
.wt-rotator19.
.www-promo.de
.wwwpromoter.
.wz-rotator2.
.x19network.
.xaogi.
.xapads.com
.xcams.com
.xcasino.
.xdrrok.com
.xpartner.
.xwell.ru
.xxxblackbook.
.yadro.
.yesmessenger.
.yourlayer.
.youtube./api/stats/
.zanox-affiliate.
.zanox.
.zarry.biz
/(.*/)adhandler/
/(.*/)partnerads.*.js
/(aff|adx|scrollad).php
/.*filesonic.gif
/.*googleads.*.js
/.*parship.*.jpg
/.adserv/
/FloatingAd.*.js
/Images/reklama..gif
/MetaAdServer/
/Werbebanner/
/ad.html
/adGallery.html
/adReload.html
/(adsense|ads|adroot|adproxy|adkit|ad_jnaught|affiliate|footerads)/
/ajax/ligatus/*
/banner/.*\.swf
/client/overture.aspx
/clientscript/affiliate.js
/cms_media/module_adbanner/
/cxo_adtech/
/displayads/
/extjs/smartad.*\.js
/gfx/layer/*
/gujAd/
/images/banners/
/interstitial.wind.js
/interstitial_18plus.js
/js/(adcontrol|adframe|selfad|omsv_adau).js
/layer/layer.php
/module/Controller_Module_Community_SearchAd
/modules/common/sponsored_links_json.php
/newad/www/delivery/
/openx/
/premiumdownload.png
/rotator/
/share/www/delivery/
/special_ads/
/vtrack/
/wp-adv/
/wp-srv/ad/
/www/delivery/
/zanox/*
1g234kj23h4.info
1l32hj4ll11.info
1oiuyoiup.info
213.174.132.50
2352356234.info
3cnce854.com
46.165.197.231
4lucysu.com
5licosy.com
62.146.71.2/beta/web/swf/PushupClient.swf
62.212.73.194
85.17.73.67
a.lakequincy.com
a.partner-versicherung.de
a3.swp.de
adlog.com.com
adserver.freenet.
adtech.panthercustomer.com
affiliate.chefgourmet.de
affiliates.a2hosting.com
ahherwebcams.
alert.scansafe.net/alert/.*
autocontext.begun.ru
banquant.com
beratersuche.rp-online.
beratersuche.welt.de
best.filmulet.ru
billabong3.wetter.
bodyc.biz
cdn.nsimg.net
cds2.freenet.
chie8oo.com
clicks.runews.radeant.
clme.biz
clunder.net
codata.ru
comm.kino.to
contactsin.mobi
contactsin.ru
crackac.com
creative.ak.fbcdn.net
d1110e4.se
depositfiles.com/payment_bornpayeu_subscribe.php
divertura.
dvasub.kipfilms.ru
dw.com.com
dynamic1.dailytech.
eas.apm.emediate.eu
einkaufswelt.t-online.
erotraf.com
extranet.leserauktion.de
fdata.over-blog.net/.*SocialPopin.js
files.bannersnack.net
freshnews.su
funny-sexxy.ru
g234kj23h4.info
golfclub.welt.de
gredinatib.
gutscheine.focus.de
gzhls.at/btn/
hiddenjs.ru
hosting.lockhosts.com
htredir.com
icqadvnew.com
id.google.*/verify/*
iftraff100.ru
imagepix.org/Images/image112.gif
images.derstandard.at/.*.swf
img.kwick.de/banners/
imghoney.com/.*swf
imgpaying./18plus.htm
ja.focus.de
join.boobfrog.com
kikiskska.ru
kka.agitos.de/
kka.idg.de
klonedaset.org
koreniztreh.net
lapeduzis.org
last.endplace.info
life.imagepix.org
linuxundich./static/gigahosting.*
loadmovie.ru
lydiz.com
makeyourblog.biz
mediaclickru.
mediadsale.ru
medianaft.ru
mobiledirectors.com
mobirollcom.ru
motionhits.com
mpmcash.com
negolist.com
neuwagen.bild.
neuwagen.welt.de
new.boobfrog.com
nexus.ensighten.com
nfm-adserver.de
notifier.avira.com
nturveev.com
nudehall.com
numking.com
nummobile.com
o0.winfuture.de
offers-service.*.
om.dsl.1und1.
openunder.net
openx-farm.ipxmuc-a.cxo.name
openx.*.
ordenn.ucoz.ru
ox.comventure.de
pap.ultramegabit.com
passul.t-online.
pay-hit.com
pic2profit.com/img/putanap/
pic2profit.com/ppb.php
pic4you.ru/rightdown/
pic5you.ru/rightdown/
picoasis.net/akoxxlayer.htm
picp2.com/img/putanap/
piwik1.datamints.com
postview.c-and-a.com
promo.awempire.
promo.javhd.com
promos.fling.com
qmebelist.ru
rcm-de.amazon.de
rotate.infowars.
rotation.linuxnewmedia.
sandugach.ucoz.ru
sd.lyc.btt.betarget.de
serv.markets.com/promo
sfileserver.glam.
sincdn.appspot.com/img/(Profi|exali)/
slivdomen.ru
sof32dsso.ru
static.fastpic.ru/rift
static.lycos-europe.net/lea/
staticpix.spin.de/bn/
staticpix.spin.de/bn/cmedia/
stats.t-online.de/include-regionales-geo-targeting-js
stats.welt.de
subscribe.hearstmags.com
traf-3rs.com
traf-monster.ru
trafers.ru
trapasol.
treetool.chip.de
turbobit.net/oexktl
usercode2.info
v2mlblue.org
versicherung.welt.de
vsexshop.ru
webmaster.pornme.com
wedinin.com
wmip.ru
wpteasertag.nzz.ch
ws.amazon.de
www.ccproxy.info
www.down1oads.com
www.enjoyops.de/chat.*
www2.glam.
www35.glam.
www8.glam.
xltraff.net







{ +block{Ranklists} }
.cyonix.to
.desire-xx.net
.star-toplist.com
.xxx-hitz.org
.xxx-ranking.net
ranklist.us
.desire-xxx.net



{ +block{Microsoft Network} }
msnvidweb.vo.msecnd.net
vms.msn.com
estj.msn.com
#.catalog.video.msn.com
#db3.stj.s-msn.com
.s-msn.com/.*track.*
#weltderwunder.de.msn.com
db3.stb.s-msn.com/i/CB/.*.swf
db3.stb.s-msn.com/i/68/.*.swf
db2.stb.s-msn.com/i/C0/.*.swf
c.microsoft.com/trans_pixel.aspx
g.msn.com/_0DEHP/
watson.telemetry.microsoft.com



{ +block{Gold&Silber Banner} }
#.marktorakel./index_files/gold_468x60.gif
.anlagegold24.de/img/.*x.*
.banner.rheingoldregio.
.bm-edelmetalle./frames/.*php
.bm-edelmetalle./frames/346x75.*.jpg
.bm-edelmetalle./frames/pf_.*.jpg
.gold-silber-anlage.de/images/GSA.gif
.gold.de/images/link_zu_uns/
.goldankauf123.
.goldmoney.com/banners/
.hartgeld.com/filesadmin/images/wb/
.imgcafe.com/view/uploads/banner.*
.kopp-verlag.de/\$WS/
.marktorakel./index_files/.*banner
.marktorakel./index_files/(gold-rush|dr-erhart|trader|standard460x65)
.marktorakel./index_files/silber-gold-verkauf-de.gif
.nice-servers./unser-finanzsystem/images/custom/.*.gif
.silber-gold-verkauf.de/resources/SGV.*
.silverbearcafe./.*banner.*
.silverbearcafe./.*berkey.*
.silverbearcafe./.*bullionbulls.*
.silverbearcafe./.*readymade.*
.survival-scout.at
.uploaded.to/img/public/i728x90.jpg
.zeitgeist-online.de/images/wbadvert/
/.*/gold_468x60.gif
/.*/krisenwelt312x91.gif
/.*/krivor180x225.gif
/.*wp-content/.*/.*banner.*.gif
/.*wp-content/.*/sgv-banner.*.gif
/.*wp-content/.*/spv310x91.gif
/.*wp-content/.*SMHAG.gif
/Transparek.gif
/images/alles-aus-einer-hand-proaurum.gif
/images/stories/hgb_01.gif
/krisenfee_logo.gif
/proaurum.*.gif
/rm_banner.gif
/wp-content/.*/Taurus2.jpg
/wp-content/.*/banner
/wp-content/.*/fairbanks2.jpg
/wp-content/.*/spannbauer.gif
/wp-content/uploads/.*180x200.*
/wp-content/uploads/.*300x250.*
/wp-content/uploads/.*_180x250.gif
/wp-content/uploads/2011/06/Kapitalschutz.gif
/wp-content/uploads/2012/08/01_125x105a_02.gif
/wp-content/uploads/.*180x400.swf
/wp-content/uploads/.*taurus_banner.jpg
www.krisenfrei.de/mh-logo.jpg
zeitenwende24.de/web/partner/
/art4u_banner468x60.jpg
/wp-content/uploads/2012/12/sw_3.gif


{ +block{Twitter, Facebook & Paypal} }
#.over-blog.
.facebook.com/common/scribe_endpoint.php
.facebook.com/dialog/oauth
.facebook.com/login/plugin_roadblock.php
.facebook.com/plugins/activity.php
.facebook.com/plugins/facepile.php
.facebook.com/plugins/fan.php
.facebook.com/plugins/like.php
.facebook.com/plugins/likebox.php
.facebook.com/plugins/recommendations_bar
.facebook.com/plugins/share_button.php
.facebook.com/widgets/like.php
.kachingle.com
.meebo.com
.meebocdn.net
.paypalobjects.com
.socialmediatabs.
.twing.
#.twitter.
.wibiya.  #nerviger toolbar
api.tweetmeme.com
apis.google.com
connect.facebook.net
error.facebook.com
vk.com/widget_like.php
widgets.twimg.com



{ +block{Tracker} }
#stats.*.

/assets/inc/adblockerzaehlung
/supportchat/(pixel|button).php
tipi.api.t-online.de
/iam_toi.js
.t-online.de/cc-adcheck-js
geolocation.t-online.
.welt.de/rem-.*/track/
rem-track.bild.de
.gosquared.com
pixel.redditmedia.com
/ptracking/
.scootloor.
webtrendsanalytics.
r.chip.de/images/pic.gif
/.*/analytics/(webtrends|EventTracker).js
/.*/js/webtrends.js
/(meter|meter-echo|tracker|analytics).js
log.pinterest.com
.googletagservices.
.sharedcount.com
.netclickstats.
/vtrack/
/log/webtracker
.youtube.com/ptracking/
metrics.brightcove.
/scripts/(tracker|track).js
.digidip.
.tracking887.
.waudit.
.mathtag.
/piwik.js
.host-tracker.
.comodoca.
.wwwstatistics.
.wmtrackinglink.
/track/
/tracker.gif
.newrelic.
.sitetag.
/vtrack/
.tracking286.
.netbiscuits.
.urban-media.
.*.de/ivw/*
.33across.
.active-tracking.
.addfreestats.
.admeld.
.adobetag.
.amazonaws.com/partner.gif
.analytics.brightedge.com
.analytics.edgekey.net
.analytics.edgesuite.
.analytics.yahoo.
.auto-ping.
.avira-analytics.
.beliebtestewebseite.de/0pixel.php
.betrad.
.blogtraffic.de/track
.chartbeat.
.clickdensity.
.clicktale.
.clickzs.
.clickzzs.
.clustrmaps.
.counterserver.
.cqcounter.
.cxo.name
.demdex.
.directtrack.
.dmtracker.
.e-referrer.
.effectivemeasure.
.eisenstein.dk
.etracker.
.fhserve.
.flagcounter.
.followistic.
.galleries.bz/track/
.gemius.
.gmodules.com
.googleusercontent.com/gadgets
.googleusercontent.com/ps/
.googleusercontent.com/tracker/*
.gostats.
.highfi-stats.
.histats.
.hypertracker.
.ic-live.
.ipcounter.
.ipv6-exp.l.google.com
.kissmetrics.
.letitbit.net/counter/
.linkbucks./track
.linkedin.com/analytics
.linkedin.com/countserv
.linkedin.com/cws/share-count
.m-pathy.
.media6degrees.
.meetrics.
.metric.gstatic.com
.mookie1.
.n-tv.de/stat/
.neostat.net
.newstogram.
.openstat.
.ourstats.
.outbrain.com
.pardot.com
.parsely.com
.perfectmarket.
.polldaddy.
.postaffiliatepro.
.profistats.
.prosieben./secure-static/
.qsstats.
.qualtrics.
.raasnet.
.radarurl.
.revolvermaps.
.ritecounter.
.salesforceliveagent.com
.scanscout.
.scorecardresearch.
.sitestat.
.srvntrk.
.statistics.
.stumbleupon.com/hostedbadge.php
.sublimevideo./_.gif
.sueddeutsche.de/l.gif
.szstats.
.tape.tv/js/adblockdetection.js
.tapstream.
.tawas.de/
.tns-counter.
.topix./t6track/
.trackalyzer.
.tracking101.
.trendcounter.
.trgt.eu
.tscapeplay.
.twyn.com
.unica.com
.vdna-assets.
.veeseo.com/tracking
.videoplaza.tv/proxy/tracker
.visiblemeasures.
.visualdna.
.websitesampling.
.webstats4u.
.wipe.de
.woopra.
.xing-share.
.yandex.ru
.ytimg.com/yts/img/pixel-.*
.zeit.de/static/flash/brightcove/ZeitPixel.swf
.zieltracker.de
/(.*/)webtrekk.*.js
/(.*/)webtrekk.swf
/.*/(track|tracking|_tracker|TrackingSystem|generictracking|ivw-faz.net|omnitracking|vInsight|adlib)\.js
/.*/GA.swf
/.*GoogleAnalytics.(swf|js)
/.*IVWAnalytics.swf
/.*IVWTracker.swf
/.*find_related_dynamic.swf
/.*oas_analytics.js
/.*webtrekk_v1-3.swf
/_oobimg.php
/analysis-logger/
/analytics/tracker
/cgi-bin/ivw/
/js/tracking/
/logger/p.gif
/php-bin/functions/ivwbox/
/revenue-js/
/stats/Logger
/tracker.(log|php)
/tvtotal/includes/php/tracking/stats.php
204st.us
a2a.lockerz.
abakus.freenet.
ac.berliner-kurier.de
analytics.*.
apis.google.com/js/plusone.js
asset.userfly.
atracktive.
b.myspace.com
beacon-1.newrelic.
beacon.securestudies.com
beriche.ru
boss.berlinonline.de
botd.wordpress.com
botd2.wordpress.com
c.spiegel.de
cc.zeit.de
com.econa.com
csi.gstatic.com
doug1izaerwt3.cloudfront.net
entry-stats.huffpost.
goku.brightcove.com/1pix.gif
hit.gemius.pl
hits.informer.com
live01.ec2.cxo.name
livepass.conviva.com
livestat.derstandard.
log.worldsoft-cms.info
lognormal.net
mm.welt.de/meter.js
npi.focus.de/cgi-bin/pagedot.gif
omni.focus.de
p.typekit.net/p.gif
partners-api.pinterest.com/v1/urls/count.json
plusone.google.
plus.google.
pulse-analytics-beacon.reutersmedia.net
rl.heise.de/images/pic.gif
s.fs.t-online.de/js.gif
somni.focus.de
stat.aldi.
stats.11media.net
stats.adobe.
stats.easystores.
stats.globalgameport.com
stats.t-online.de/ati-js/
stats.tradekey.com
stats.vertriebsassistent.de
stats.wordpress.com
tags.bluekai.com/site/
track.ft.com
track.gawker.com
track.netshelter.net
tracker.*.
traf.visit-x.net
traffic.brand-wall.net
widgets.pinterest.com/v3/pidgets/log/



{ +block{domain parking} }
.debtowedzz.
.drugstoreschool.
.findultimatehealth.
.newhealthclinic.
.sedo.com
.urlquickfind.
.searchremagnified.com
.dsparking.
.parkingpremium.
/domainads/


{ +block{Test} }
st.chatango.com


{ -block }
.jamendo.com
.date-click.de
.adtmag.com
adressbuch.web.de
.pagerduty.com

{ +fast-redirects{check-decoded-url} }
# freemailng*.web.de



# The URLs of dynamically generated banners, especially from large banner
# farms, often don't use the well-known image file name extensions, which
# makes it impossible for Privoxy to guess the file type just by looking
# at the URL. 
# You can use the +block-as-image alias defined above for these cases.
# Note that objects which match this rule but then turn out NOT to be an
# image are typically rendered as a "broken image" icon by the browser.
# Use cautiously.
#
{ +block-as-image }
#.doubleclick.net
#/Realmedia/ads/
#ar.atwola.com/

# Now you noticed that the default configuration breaks Forbes
# Magazine, but you were too lazy to find out which action is the
# culprit, and you were again too lazy to give feedback, so you just
# used the fragile alias on the site, and -- whoa! -- it worked. The
# 'fragile' aliases disables those actions that are most likely to break
# a site. Also, good for testing purposes to see if it is Privoxy that
# is causing the problem or not.
# 
{ fragile }
#.forbes.com
www.kwick.de/dialoge/tinymce/plugins/
www.kwick.de/dialoge/tinymce/plugins/advimage/editor_plugin_src.js
www.kwick.de/dialoge/tinymce/plugins/advlink/editor_plugin_src.js

# TriMoon
.kayseri.bel.tr
.curse.com
.aeriagames.com
.gameloft.com/ads/adserver/web/fullscreen/*
.gamersfirst.com
.hdfilmsitesi.com.tr
.hsbc.com
.hsbc.com.tr
.kabam.com
.kocasinan.bel.tr
.leagueoflegends.com
.my.mail.ru
.sahibinden.com
.samfirmware.com
.sammobile.com
.samsung.com
.samsungcsportal.com
.static.pornhub.phncdn.com
.the-west.net
.turkcell.com.tr
.vk.com
.wikia.com
.xda-developers.com
.accounts.firefox.com
accounts.firefox.com
autoupdate-revision.unity3d.com
api.geo.kontagent.net
canvas-live.gop3.nl
cdnapi.kaltura.com
download.windowsupdate.com
minecraft.gamepedia.com
o.gez.io
perfectworld.vanillaforums.com/*
shaiyatora.square7.ch
tw-db.info
www.dizitvhd.net


# Here are some sites we wish to support, and we will allow their ads
# through.
#
{ allow-ads }
#.sourceforge.net
#.slashdot.org
#.osdn.net

# user.action is generally the best place to define exceptions and
# additions to the default policies of default.action. Some actions are
# safe to have their default policies set here though. So let's set a
# default policy to have a 'blank' image as opposed to the checkerboard
# pattern for ALL sites. '/' of course matches all URLs.
# patterns:
#
{ +set-image-blocker{blank} }
#/

{ +filter{nohttps} }
.melango.de
img.kwick.de
www.xing-share.com


## set vi:nowrap tw=72
